import Container from "@/components/shared/common/container";
import Heading from "@/components/shared/common/heading";
import { text } from "@/data";
import React from "react";

export const metadata = {
  title: "About us | Al Raza Hospital - Faisalabad",
  description: "Generated by create next app",
};

const AboutUs = () => {
  return (
    <Container parentStyle={"py-10"}>
      <Heading
        level={2}
        CustomHeadingStyle="!text-lg !font-normal"
        CustomHeading={"GENERAL INFO"}
      />
      <Heading
        level={1}
        CustomHeadingStyle=" !my-2"
        CustomHeading={"ABOUT US"}
      />
      {text}
    </Container>
  );
};

export default AboutUs;
