import React from 'react'

export const metadata = {
  title: "About us | Al Raza Hospital - Faisalabad",
  description: "Generated by create next app",
};

const AboutUs = () => {


  return (
    <div>AboutUs </div>
  )
}

export default AboutUs